FROM python:3.12-alpine

WORKDIR /app

COPY pyproject.toml poetry.lock* ./ # poetry.lock might not exist yet

RUN pip install poetry && poetry install --no-root --no-dev

COPY ./app /app/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
