"""Add content_tsvector column to document_chunks table for FTS

Revision ID: 2c2953cb38ac
Revises: 6dfd63604852
Create Date: 2026-09-23 17:52:14.799088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2953cb38ac'
down_revision: Union[str, None] = '6dfd63604852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content_tsvector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'content_tsvector')
    # ### end Alembic commands ###
