"""Add embedding column and ingestion fields to document_chunks and document tables

Revision ID: 6dfd63604852
Revises: e9462f97bdce
Create Date: 2026-09-23 17:24:11.577762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfd63604852'
down_revision: Union[str, None] = 'e9462f97bdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
