"""Add ingestion-related fields to document and document_chunk tables

Revision ID: 7404f9640d13
Revises: de6275d4b643
Create Date: 2026-09-23 16:51:45.914381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7404f9640d13'
down_revision: Union[str, None] = 'de6275d4b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
