"""Add ingestion-related fields and embedding/tsvector columns

Revision ID: a8d398fe4ed3
Revises: 2c2953cb38ac
Create Date: 2026-09-24 14:56:40.077348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d398fe4ed3'
down_revision: Union[str, None] = '2c2953cb38ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
