"""Add hashed_password and is_active to users table

Revision ID: e911c7329457
Revises: 4a72c52ef3dc
Create Date: 2026-09-24 15:24:47.832918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e911c7329457'
down_revision: Union[str, None] = '4a72c52ef3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
