"""Add embedding column and ingestion fields to document_chunks and document tables

Revision ID: e9462f97bdce
Revises: 7404f9640d13
Create Date: 2026-09-23 17:20:49.160786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e9462f97bdce'
down_revision: Union[str, None] = '7404f9640d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
